version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"  # Host:Container port

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}  # Passed from .env file
    ports:
      - "3001:3001"
    depends_on:
      - frontend